package View;

import Utilitarios.conexao;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public final class frmCaixa extends javax.swing.JFrame {
   

    conexao con_venda;
    conexao con_cliente;
    conexao con_produto;
    conexao con_local;
    conexao con_desconto;
    
    public void mostrarDadosVenda(){
        try{
            txtCodProduto_caixa.setText(con_venda.resultset.getString("CODPROD"));
            txtNomecliente_caixa.setText(con_venda.resultset.getString("CODCLI"));
            txtDescricao_caixa.setText(con_produto.resultset.getString("DESCRICAO"));
        }catch (SQLException erro){
            JOptionPane.showMessageDialog(null,"Não localizou dados" + erro.getMessage());
        }
    }
 
    public frmCaixa() {
        initComponents();
        con_venda = new conexao();
        con_venda.conecta();
        con_venda.executaSQL("select * from venda order by ID_VENDA");
        
        con_cliente = new conexao();
        con_cliente.conecta();
        con_cliente.executaSQL("select * from cliente order by CODCLI");
        
        con_produto = new conexao();
        con_produto.conecta();
        con_produto.executaSQL("select * from produto order by CODPROD");
        
        con_local = new conexao();
        con_local.conecta();
        con_local.executaSQL("select * from localidade order by CODLOCAL");
        
        con_desconto = new conexao();
        con_desconto.conecta();
        con_desconto.executaSQL("select * from desconto order by ID_DESCONTO");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PDV = new javax.swing.JTabbedPane();
        panelCaixa = new javax.swing.JPanel();
        lblCodProduto_caixa = new javax.swing.JLabel();
        lblQtd_caixa = new javax.swing.JLabel();
        txtQtd_caixa = new javax.swing.JTextField();
        btnVender_caixa = new javax.swing.JButton();
        btnExcluir_caixa = new javax.swing.JButton();
        lblDescricao_caixa = new javax.swing.JLabel();
        txtDescricao_caixa = new javax.swing.JTextField();
        tabelaProduto_caixa = new javax.swing.JScrollPane();
        tblProdutos_caixa = new javax.swing.JTable();
        lblTotalCompra_caixa = new javax.swing.JLabel();
        txtTotalCompra_caixa = new javax.swing.JTextField();
        btnFechar_caixa = new javax.swing.JButton();
        lblTitulo_caixa = new javax.swing.JLabel();
        lblCliente_caixa = new javax.swing.JLabel();
        lblLocalVenda_caixa = new javax.swing.JLabel();
        txtNomecliente_caixa = new javax.swing.JTextField();
        txtLocalVenda_caixa = new javax.swing.JTextField();
        txtCodProduto_caixa = new javax.swing.JTextField();
        lblCodCli_cliente = new javax.swing.JLabel();
        txtCodCli_cliente = new javax.swing.JTextField();
        cliente = new javax.swing.JPanel();
        lblTitulo_cliente = new javax.swing.JLabel();
        lblNome_cliente = new javax.swing.JLabel();
        txtNome_cliente = new javax.swing.JTextField();
        lblCod_cliente = new javax.swing.JLabel();
        txtcodcliente = new javax.swing.JTextField();
        lblBonus_cliente = new javax.swing.JLabel();
        txtbonus_cliente = new javax.swing.JTextField();
        lblPerfil = new javax.swing.JLabel();
        comboPerfil_cliente = new javax.swing.JComboBox<>();
        btnSalvar_cliente = new javax.swing.JButton();
        produto = new javax.swing.JPanel();
        lblTitulo_produto = new javax.swing.JLabel();
        lblCod_produto = new javax.swing.JLabel();
        txtcodprod_produto = new javax.swing.JTextField();
        lblCodLocal = new javax.swing.JLabel();
        txtcodlocal_produto = new javax.swing.JTextField();
        lblNomeLocal_produto = new javax.swing.JLabel();
        txtnomelocal = new javax.swing.JTextField();
        lblDescricao_produto = new javax.swing.JLabel();
        txtdescricao_produto = new javax.swing.JTextField();
        lblQtdEstoque_produto = new javax.swing.JLabel();
        spnQtdEstoque_produto = new javax.swing.JSpinner();
        lblPrecoUnit_produto = new javax.swing.JLabel();
        txtprecoUnit_produto = new javax.swing.JFormattedTextField();
        btnSalvar_produto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTROLE DE CAIXA");
        setBackground(new java.awt.Color(153, 153, 153));

        PDV.setBackground(new java.awt.Color(153, 153, 153));
        PDV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PDV.setForeground(new java.awt.Color(0, 0, 153));

        panelCaixa.setBackground(new java.awt.Color(229, 255, 255));

        lblCodProduto_caixa.setForeground(new java.awt.Color(0, 0, 153));
        lblCodProduto_caixa.setText("Código do produto:");

        lblQtd_caixa.setForeground(new java.awt.Color(0, 0, 153));
        lblQtd_caixa.setText("Quantidade:");

        txtQtd_caixa.setToolTipText("");

        btnVender_caixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Actions-dialog-ok-apply-icon.png"))); // NOI18N
        btnVender_caixa.setText("Vender");
        btnVender_caixa.setToolTipText("");
        btnVender_caixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVender_caixaActionPerformed(evt);
            }
        });

        btnExcluir_caixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Actions-edit-delete-icon.png"))); // NOI18N
        btnExcluir_caixa.setText("Cancelar");

        lblDescricao_caixa.setForeground(new java.awt.Color(0, 0, 153));
        lblDescricao_caixa.setText("Descrição do Produto");
        lblDescricao_caixa.setToolTipText("");

        tblProdutos_caixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Quantidade", "Preço Unitário", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProduto_caixa.setViewportView(tblProdutos_caixa);

        lblTotalCompra_caixa.setForeground(new java.awt.Color(0, 0, 153));
        lblTotalCompra_caixa.setText("Total da Compra:");

        txtTotalCompra_caixa.setEditable(false);
        txtTotalCompra_caixa.setToolTipText("");

        btnFechar_caixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logout-icon.png"))); // NOI18N
        btnFechar_caixa.setText("Fechar");

        lblTitulo_caixa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo_caixa.setForeground(new java.awt.Color(0, 0, 153));
        lblTitulo_caixa.setText("CAIXA LIVRE");

        lblCliente_caixa.setForeground(new java.awt.Color(0, 0, 153));
        lblCliente_caixa.setText("Cliente:");

        lblLocalVenda_caixa.setForeground(new java.awt.Color(0, 0, 153));
        lblLocalVenda_caixa.setText("Local de Venda:");

        txtNomecliente_caixa.setEditable(false);
        txtNomecliente_caixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomecliente_caixaActionPerformed(evt);
            }
        });

        lblCodCli_cliente.setForeground(new java.awt.Color(0, 0, 153));
        lblCodCli_cliente.setText("Codigo do cliente:");

        javax.swing.GroupLayout panelCaixaLayout = new javax.swing.GroupLayout(panelCaixa);
        panelCaixa.setLayout(panelCaixaLayout);
        panelCaixaLayout.setHorizontalGroup(
            panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaixaLayout.createSequentialGroup()
                .addGroup(panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCaixaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTotalCompra_caixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalCompra_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCaixaLayout.createSequentialGroup()
                        .addGroup(panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCaixaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDescricao_caixa))
                            .addGroup(panelCaixaLayout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(lblTitulo_caixa)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCaixaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabelaProduto_caixa)))
                .addContainerGap())
            .addGroup(panelCaixaLayout.createSequentialGroup()
                .addGroup(panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCaixaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodProduto_caixa)
                            .addComponent(txtCodProduto_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQtd_caixa)
                            .addComponent(txtQtd_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLocalVenda_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLocalVenda_caixa)))
                    .addGroup(panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelCaixaLayout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addComponent(btnFechar_caixa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnExcluir_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnVender_caixa))
                        .addGroup(panelCaixaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtDescricao_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCaixaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelCaixaLayout.createSequentialGroup()
                                    .addComponent(lblCodCli_cliente)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(txtCodCli_cliente))
                            .addGap(18, 18, 18)
                            .addGroup(panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCliente_caixa)
                                .addComponent(txtNomecliente_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        panelCaixaLayout.setVerticalGroup(
            panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaixaLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblTitulo_caixa)
                .addGap(23, 23, 23)
                .addGroup(panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente_caixa)
                    .addComponent(lblCodCli_cliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomecliente_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodCli_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodProduto_caixa)
                    .addComponent(lblQtd_caixa)
                    .addComponent(lblLocalVenda_caixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodProduto_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtd_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocalVenda_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lblDescricao_caixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDescricao_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(tabelaProduto_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalCompra_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalCompra_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar_caixa)
                    .addComponent(btnExcluir_caixa)
                    .addComponent(btnVender_caixa))
                .addGap(40, 40, 40))
        );

        PDV.addTab("CAIXA", new javax.swing.ImageIcon(getClass().getResource("/icones/cashier_icon-icons.com_53629.png")), panelCaixa); // NOI18N

        cliente.setBackground(new java.awt.Color(229, 255, 255));

        lblTitulo_cliente.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo_cliente.setForeground(new java.awt.Color(0, 0, 153));
        lblTitulo_cliente.setText("CADASTRAR NOVO CLIENTE");

        lblNome_cliente.setText("Nome:");

        txtNome_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome_clienteActionPerformed(evt);
            }
        });

        lblCod_cliente.setText("Código do cliente:");

        txtcodcliente.setEditable(false);

        lblBonus_cliente.setText("Bônus:");

        lblPerfil.setText("Perfil:");

        comboPerfil_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P - Pequeno", "M - Médio", "G - Grande" }));

        btnSalvar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/AwesomeScreenshot-TRE-SP-2019-07-26-23-07-03.png"))); // NOI18N
        btnSalvar_cliente.setText("Salvar");
        btnSalvar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar_clienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clienteLayout = new javax.swing.GroupLayout(cliente);
        cliente.setLayout(clienteLayout);
        clienteLayout.setHorizontalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteLayout.createSequentialGroup()
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPerfil)
                        .addGap(18, 18, 18)
                        .addComponent(comboPerfil_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNome_cliente)
                        .addGap(8, 8, 8)
                        .addComponent(txtNome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblCod_cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcodcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(lblBonus_cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbonus_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btnSalvar_cliente))
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(lblTitulo_cliente)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        clienteLayout.setVerticalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblTitulo_cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCod_cliente)
                    .addComponent(txtbonus_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBonus_cliente))
                .addGap(33, 33, 33)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome_cliente)
                    .addComponent(txtNome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPerfil_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPerfil))
                .addGap(111, 111, 111)
                .addComponent(btnSalvar_cliente)
                .addGap(47, 47, 47))
        );

        PDV.addTab("INCLUIR CLIENTE", new javax.swing.ImageIcon(getClass().getResource("/icones/bootloader_users_person_people_6080.png")), cliente); // NOI18N

        produto.setBackground(new java.awt.Color(229, 255, 255));

        lblTitulo_produto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo_produto.setForeground(new java.awt.Color(0, 0, 153));
        lblTitulo_produto.setText("CADASTRAR NOVO PRODUTO");

        lblCod_produto.setText("Código do produto: ");

        txtcodprod_produto.setEditable(false);

        lblCodLocal.setText("Código do local:");

        lblNomeLocal_produto.setText("Nome do Local:");

        txtnomelocal.setEditable(false);

        lblDescricao_produto.setText("Descrição do produto:");

        lblQtdEstoque_produto.setText("Quantidade no Estoque:");

        lblPrecoUnit_produto.setText("Preço Unitário:");

        txtprecoUnit_produto.setText("R$0,00");

        btnSalvar_produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/AwesomeScreenshot-TRE-SP-2019-07-26-23-07-03.png"))); // NOI18N
        btnSalvar_produto.setText("Salvar");

        javax.swing.GroupLayout produtoLayout = new javax.swing.GroupLayout(produto);
        produto.setLayout(produtoLayout);
        produtoLayout.setHorizontalGroup(
            produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produtoLayout.createSequentialGroup()
                .addGroup(produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(produtoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(produtoLayout.createSequentialGroup()
                                    .addComponent(lblDescricao_produto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtdescricao_produto))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, produtoLayout.createSequentialGroup()
                                    .addComponent(lblCodLocal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtcodlocal_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblNomeLocal_produto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtnomelocal, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, produtoLayout.createSequentialGroup()
                                .addComponent(lblQtdEstoque_produto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnQtdEstoque_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPrecoUnit_produto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSalvar_produto)
                                    .addComponent(txtprecoUnit_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(produtoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCod_produto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcodprod_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(produtoLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(lblTitulo_produto)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        produtoLayout.setVerticalGroup(
            produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produtoLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(lblTitulo_produto)
                .addGap(72, 72, 72)
                .addGroup(produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod_produto)
                    .addComponent(txtcodprod_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodLocal)
                    .addComponent(txtcodlocal_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeLocal_produto)
                    .addComponent(txtnomelocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao_produto)
                    .addComponent(txtdescricao_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdEstoque_produto)
                    .addComponent(spnQtdEstoque_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecoUnit_produto)
                    .addComponent(txtprecoUnit_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btnSalvar_produto)
                .addGap(52, 52, 52))
        );

        PDV.addTab("INCLUIR PRODUTO", null, produto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PDV, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PDV, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVender_caixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVender_caixaActionPerformed
     String codProd = txtCodProduto_caixa.getText();
     String local = txtLocalVenda_caixa.getText();
     String codCli = txtNomecliente_caixa.getText();
     String qtdProd = txtQtd_caixa.getText();
     String descricao = txtDescricao_caixa.getText();
     String Nome = txtNomecliente_caixa.getText();
     String valortotal = txtTotalCompra_caixa.getText();
     
     try{
         
         String insert_sql = "insert into venda (CODCLI, CODPROD, CODLOCAL, QTD_VENDA, VALOR_TOTAL) values ('" + codCli + "','" + codProd + "','" +
                 local + "','" + qtdProd + "','" + valortotal +"')";
         
         con_venda.statement.executeUpdate(insert_sql);
         JOptionPane.showMessageDialog(null, "Venda realizada com sucesso!");
         
         
         con_venda.resultset = con_venda.statement.executeQuery("select * from venda order by ID_VENDA");
         con_venda.resultset.first();
     }catch (SQLException errosql){
         JOptionPane.showMessageDialog(null,"Erro ao realizar a venda! " + errosql);
     }
    }//GEN-LAST:event_btnVender_caixaActionPerformed

    private void txtNomecliente_caixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomecliente_caixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomecliente_caixaActionPerformed

    private void txtNome_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome_clienteActionPerformed

    private void btnSalvar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar_clienteActionPerformed
        String nome = txtNome_cliente.getText();
        String local = txtLocalVenda_caixa.getText();
        String cod = txtCodProduto_caixa.getText();
        String qtd = txtQtd_caixa.getText();
        String descricao = txtDescricao_caixa.getText();
    }//GEN-LAST:event_btnSalvar_clienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PDV;
    private javax.swing.JButton btnExcluir_caixa;
    private javax.swing.JButton btnFechar_caixa;
    private javax.swing.JButton btnSalvar_cliente;
    private javax.swing.JButton btnSalvar_produto;
    private javax.swing.JButton btnVender_caixa;
    private javax.swing.JPanel cliente;
    private javax.swing.JComboBox<String> comboPerfil_cliente;
    private javax.swing.JLabel lblBonus_cliente;
    private javax.swing.JLabel lblCliente_caixa;
    private javax.swing.JLabel lblCodCli_cliente;
    private javax.swing.JLabel lblCodLocal;
    private javax.swing.JLabel lblCodProduto_caixa;
    private javax.swing.JLabel lblCod_cliente;
    private javax.swing.JLabel lblCod_produto;
    private javax.swing.JLabel lblDescricao_caixa;
    private javax.swing.JLabel lblDescricao_produto;
    private javax.swing.JLabel lblLocalVenda_caixa;
    private javax.swing.JLabel lblNomeLocal_produto;
    private javax.swing.JLabel lblNome_cliente;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblPrecoUnit_produto;
    private javax.swing.JLabel lblQtdEstoque_produto;
    private javax.swing.JLabel lblQtd_caixa;
    private javax.swing.JLabel lblTitulo_caixa;
    private javax.swing.JLabel lblTitulo_cliente;
    private javax.swing.JLabel lblTitulo_produto;
    private javax.swing.JLabel lblTotalCompra_caixa;
    private javax.swing.JPanel panelCaixa;
    private javax.swing.JPanel produto;
    private javax.swing.JSpinner spnQtdEstoque_produto;
    private javax.swing.JScrollPane tabelaProduto_caixa;
    private javax.swing.JTable tblProdutos_caixa;
    private javax.swing.JTextField txtCodCli_cliente;
    private javax.swing.JTextField txtCodProduto_caixa;
    private javax.swing.JTextField txtDescricao_caixa;
    private javax.swing.JTextField txtLocalVenda_caixa;
    private javax.swing.JTextField txtNome_cliente;
    private javax.swing.JTextField txtNomecliente_caixa;
    private javax.swing.JTextField txtQtd_caixa;
    private javax.swing.JTextField txtTotalCompra_caixa;
    private javax.swing.JTextField txtbonus_cliente;
    private javax.swing.JTextField txtcodcliente;
    private javax.swing.JTextField txtcodlocal_produto;
    private javax.swing.JTextField txtcodprod_produto;
    private javax.swing.JTextField txtdescricao_produto;
    private javax.swing.JTextField txtnomelocal;
    private javax.swing.JFormattedTextField txtprecoUnit_produto;
    // End of variables declaration//GEN-END:variables
}
